name: Deploy Website with Data

on:
  schedule:
    - cron: "14 3 * * *" # 3:14 AM UTC
    - cron: "47 9 * * *" # 9:47 AM UTC
    - cron: "22 15 * * *" # 3:22 PM UTC
    - cron: "5 20 * * *" # 8:05 PM UTC
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install requests

      - name: Generate Data
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          # 75% chance to skip the update (since it schedules 4 times a day, averages to ~1 run/day)
          if [ $(( $RANDOM % 100 )) -lt 96 ]; then
            echo "Skipping update to save minutes and keep activity natural."
            exit 0
          fi

          python generate_data.py # This creates data.json in the current folder

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
